Update publications.yml
rs-station/rs-station.github.io pull request #29
Opened 2024-10-21 18:52 UTC by dennisbrookner

Update the lauedials citation to point to the paper, rather than the pre-print

2024-10-22 20:55 UTC, kmdalton requested changes
We should use DOIs when possible for the URLs. They are at least meant to be more permanent / reliable.

2024-10-22 20:55 UTC, kmdalton commented on _data/publications.yml
> +  url: https://pubs.aip.org/aca/sdy/article/11/5/054701/3315187/Laue-DIALS-Open-source-software-for-polychromatic
this URL should use the DOI, [https://doi.org/10.1063/4.0000265](https://doi.org/10.1063/4.0000265)

2024-10-29 00:34 UTC, DHekstra approved these changes
This now meets Kevin's request (use DOI) and mine (point to actual paper). I think we're done!

2024-10-29 00:35 UTC, DHekstra commented
@kmdalton, I think this is waiting for you.

2024-10-29 00:38 UTC, kmdalton approved these changes
Looks good to me, thanks!

2024-10-29 00:38 UTC, merged